version: "3.8"

services:

  serverpostgresql:
    image: postgres:15
    container_name: serverpostgresql
    hostname: serverpostgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: bookon
      POSTGRES_USER: server
      POSTGRES_PASSWORD: server
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    networks:
      - bookon-network

  servermongo:
    image: mongo:latest
    container_name: servermongo
    hostname: servermongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: server
      MONGO_INITDB_ROOT_PASSWORD: server
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/server --quiet
      start_period: 10s
    volumes:
      - ./data/mongo:/data/db
      - ./docker/mongo:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      - bookon-network
      
  jenkins:
    image: jenkinsci/blueocean
    ports:
      - '18099:8099'
    volumes:
      - 'jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  jenkins_home:
    driver: local

networks:
  bookon-network:
    driver: bridge
