version: "3.8"

services:

  bookonpostgresql:
    image: postgres:latest
    container_name: bookonpostgresql
    hostname: bookonpostgresql
    restart: unless-stopped
    environment:
      - "POSTGRES_DB=bookon"
      - "POSTGRES_USER=bookon"
      - "POSTGRES_PASSWORD=bookon"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data 
    ports:
      - "15432:5432"
    networks:
      - bookon-network
      
  bookonmongo:
    image: mongo:latest
    container_name: bookonmongo
    hostname: bookonmongo
    restart: unless-stopped
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=bookon"
      - "MONGO_INITDB_ROOT_PASSWORD=bookon"
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/bookon --quiet
      start_period: 10s
    volumes:
      - ./data/mongo:/data/db
      - ./docker/mongo:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      - bookon-network

networks:
  bookon-network:
    driver: bridge